"""empty message

Revision ID: bad74d6bb056
Revises: bb950c71a7c6
Create Date: 2023-12-01 22:49:09.051965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad74d6bb056'
down_revision: Union[str, None] = 'bb950c71a7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('total_discount', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', 'CANCELED', name='order_status'), server_default='PENDING', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('order_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_pkey'))
    )
    op.create_index(op.f('order_id_idx'), 'order', ['id'], unique=False)
    op.create_table('order_product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('order_product_order_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('order_product_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_product_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product')
    op.drop_index(op.f('order_id_idx'), table_name='order')
    op.drop_table('order')
    sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', 'CANCELED', name='order_status').drop(op.get_bind())
    # ### end Alembic commands ###
