"""empty message

Revision ID: dc532918eb39
Revises: c676b48f0840
Create Date: 2023-12-05 20:54:21.467054

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc532918eb39'
down_revision: Union[str, None] = 'c676b48f0840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocode',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('promocode', sa.String(length=50), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.CheckConstraint('discount <= 100', name=op.f('promocode_max_discount_check')),
    sa.CheckConstraint('discount > 0', name=op.f('promocode_min_discount_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('promocode_pkey')),
    sa.UniqueConstraint('promocode', name=op.f('promocode_promocode_key'))
    )
    op.create_index(op.f('promocode_id_idx'), 'promocode', ['id'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('cart_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('cart_user_id_key'))
    )
    op.create_index(op.f('cart_id_idx'), 'cart', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('total_discount', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('promocode', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'COMPLETED', 'CANCELED', name='order_status'), server_default='PENDING', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('order_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_pkey'))
    )
    op.create_index(op.f('order_id_idx'), 'order', ['id'], unique=False)
    op.create_table('cart_product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name=op.f('cart_product_cart_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('cart_product_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_product_pkey'))
    )
    op.create_table('order_product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('order_product_order_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('order_product_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_product_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product')
    op.drop_table('cart_product')
    op.drop_index(op.f('order_id_idx'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('cart_id_idx'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('promocode_id_idx'), table_name='promocode')
    op.drop_table('promocode')
    sa.Enum(name='order_status').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
