"""empty message

Revision ID: 2d72f676c37f
Revises: 1003855ee3b9
Create Date: 2024-01-22 21:16:47.199669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d72f676c37f'
down_revision: Union[str, None] = '1003855ee3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.drop_constraint('cart_product_product_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key(op.f('cart_product_cart_id_fkey'), 'cart_product', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cart_product_product_id_fkey'), 'cart_product', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_user_id_fkey'), 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_product_product_id_fkey', 'order_product', type_='foreignkey')
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key(op.f('order_product_product_id_fkey'), 'order_product', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('order_product_order_id_fkey'), 'order_product', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_category_product_id_fkey', 'product_category', type_='foreignkey')
    op.drop_constraint('product_category_category_id_fkey', 'product_category', type_='foreignkey')
    op.create_foreign_key(op.f('product_category_category_id_fkey'), 'product_category', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('product_category_product_id_fkey'), 'product_category', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_category_product_id_fkey'), 'product_category', type_='foreignkey')
    op.drop_constraint(op.f('product_category_category_id_fkey'), 'product_category', type_='foreignkey')
    op.create_foreign_key('product_category_category_id_fkey', 'product_category', 'category', ['category_id'], ['id'])
    op.create_foreign_key('product_category_product_id_fkey', 'product_category', 'product', ['product_id'], ['id'])
    op.drop_constraint(op.f('order_product_order_id_fkey'), 'order_product', type_='foreignkey')
    op.drop_constraint(op.f('order_product_product_id_fkey'), 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'])
    op.create_foreign_key('order_product_product_id_fkey', 'order_product', 'product', ['product_id'], ['id'])
    op.drop_constraint(op.f('order_user_id_fkey'), 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('cart_product_product_id_fkey'), 'cart_product', type_='foreignkey')
    op.drop_constraint(op.f('cart_product_cart_id_fkey'), 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_product_id_fkey', 'cart_product', 'product', ['product_id'], ['id'])
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'])
    # ### end Alembic commands ###
